CREATE TABLE DADOSFUNCIONARIOS(
	ID_FUNCIONARIO INT AUTO_INCREMENT,
	MATRICULA INT NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	CARGO VARCHAR(20) NOT NULL,
	CONTATO_TELEFONE NUMERIC(12),
	E_MAIL VARCHAR(70),
	SERVICO_ALOCADO VARCHAR(50),
    
    PRIMARY KEY (ID_FUNCIONARIO)
);