CREATE TABLE DADOSUSUARIOS(
	ID_USUARIO INT AUTO_INCREMENT,
	PRONTUARIO INT,

	NOME VARCHAR(50) NOT NULL,
	NOMESOCIAL VARCHAR(50),
	APELIDO VARCHAR (20),
	NOMEMAE VARCHAR(50),
	NOMEPAI VARCHAR(50),
	DATANASCIMENTO DATE,
	CPF NUMERIC(11),
	NIS NUMERIC(13),
	RG VARCHAR(15),
	SERVICO_QUE_ATENDE VARCHAR(50),
    
    PRIMARY KEY (ID_USUARIO)
);