CREATE TABLE ATENDIMENTO
(
    ID_ATENDIMENTO INT AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_FUNCIONARIO INT NOT NULL,
    DATA_ATENDIMENTO DATE NOT NULL,
    COMENTARIOS VARCHAR(200),

    PRIMARY KEY (ID_ATENDIMENTO),
    
    FOREIGN KEY ID_USUARIO_FK (ID_USUARIO)
    REFERENCES DADOSUSUARIOS(ID_USUARIO),
    FOREIGN KEY ID_FUNCIONARIO_FK (ID_FUNCIONARIO)
    REFERENCES DADOSFUNCIONARIOS(ID_FUNCIONARIO)
);