CREATE TABLE SERVICO
(
    ID_SERVICO INT AUTO_INCREMENT,
    NOME_DO_SERVICO VARCHAR(60) NOT NULL,
    TELEFONE VARCHAR(14) NOT NULL,
    E_MAIL_DE_CONTATO VARCHAR(40),

    PRIMARY KEY ID_SERVICO

);